[animations]
#Choose your preferred animation speed (1-15)
# Default: 8.0
# Range: 1.0 ~ 15.0
animationSpeed = 8.0
#Enable or disable swimming animation
enableSwimmingAnimation = true
#Swing animation speed (6-12)
# Default: 9
# Range: 6 ~ 12
swingSpeed = 9
#Enable or disable climb and crawl animation
enableClimbAndCrawlAnimation = false
#Enable or disable punching animation
enablePunchingAnimation = true

[positions]
#Viewmodel X Offset
# Default: 0.0
# Range: -10.0 ~ 10.0
viewmodelXOffset = 0.0
#Viewmodel Y Offset
# Default: 0.0
# Range: -10.0 ~ 10.0
viewmodelYOffset = 0.0
#Viewmodel Z Offset
# Default: 0.0
# Range: -10.0 ~ 10.0
viewmodelZOffset = 0.0

[misc]
#Enable MB3D compatibility mode
mb3DCompat = false

[modRenderExclusions]
#List of mod IDs whose items handle their own first-person rendering. Hold My Items will skip its custom logic when such an item is held.
modsThatHandleTheirOwnRendering = ["pointblank", "jeg"]

[itemRenderExclusions]
#List of items to disable custom rendering for. Can use patterns with * as wildcard.
disabledItems = ["cobblemon:*", "create*", "cobble*", "iron*"]
