#These configs are general configs that don't fit any other category.
[general]
	#Listens to specific key for when it is held. Defaults to sprint if we can't find your specified key.
	swapKeyListen = "key.sprint"
	#Listens to specific key for when it is held. Defaults to sneak if we can't find your specified key.
	swapSlotListen = ""
	#Do you need to hold the hotbar swap key to be able to swap a slot?
	requireSwapKeyForSlot = true
	#When selecting a row/slot to swap, ignore the empty ones?
	ignoreEmptySlots = false
	#Scroll rows in the reverse order?
	invertScrollDirection = true
	#These slots are ignored when changing rows/slots (slots are counted 0, 1, 2...8)
	#
	#Add/remove a slot by holding the swap slot key then hitting the swap row key
	ignoredSlots = []
	#The scale for the item when rendering a possible swap
	# Default: 0.65
	# Range: 0.0 ~ 2.0
	itemScale = 1.0
	#Horizontal offset when rendering the item
	# Default: 20
	# Range: -40 ~ 40
	itemOffsetX = 0
	#Vertical offset when rendering the item
	# Default: 20
	# Range: -40 ~ 40
	itemOffsetY = 15
