enabled = false
save_enabled_state = false
# Default: 3.0
# Range: 0.01 ~ 10000.0
scale_x = 3.0
# Default: 3.0
# Range: 0.01 ~ 10000.0
scale_y = 3.0
# Default: -1000.0
# Range: -1000.0 ~ 0.0
min_distance = -1000.0
# Default: 1000.0
# Range: 0.0 ~ 1000.0
max_distance = 1000.0
fixed = false
# Default: 0.0
# Range: 0.0 ~ 360.0
fixed_yaw = 0.0
# Default: 0.0
# Range: -90.0 ~ 90.0
fixed_pitch = 0.0
# Default: 3.0
# Range: 0.0 ~ 90.0
fixed_rotate_speed_x = 3.0
# Default: 3.0
# Range: 0.0 ~ 90.0
fixed_rotate_speed_y = 3.0
auto_third_person = true
